torapura/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # http(s)://ホスト名/以下のパスがadmin/にマッチングした場合
    # admin.site.urlsを呼び出し、Django管理サイトを表示する
    path('admin/', admin.site.urls),

    # http(s)://ホスト名/へのアクセスはtrapuraappの
    # URLconf(urls.py)を呼び出す
    path('', include('torapuraapp.urls')),

]

torapuraapp/urls.py
from django.urls import path

from . import views
from .views import GalleryView, PlanView, PlanResultView

# URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = "torapuraapp"

# URLパターンを登録するためのリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスが''(無し)の場合
    # viewsモジュールのIndexViewを実行
    # URLパターン名は'index'
    path("", views.IndexView.as_view(), name="index"),
    path("gallery", views.Post_List_View.as_view(), name="gallery"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path("contact_user", views.ContactUserView.as_view(), name="contact_user"),
    path("contact_company", views.ContactCompanyView.as_view(), name="contact_company"),
    path("", GalleryView.as_view(), name="post_list"),
    path("plan", views.PlanView.as_view(), name="plan"),
    path("plan/result/", views.PlanResultView.as_view(), name="plan_result"),
]

torapuraapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    date = models.DateField(default=timezone.now)  # 手動入力または自動入力可能な日付

    def __str__(self):
        return self.title

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField("タイトル", max_length=200)
    content = models.TextField("本文")
    created = models.DateTimeField("作成日", default=timezone.now)

    def __str__(self):
        return self.title
        
class Plan(models.Model):
    place = models.CharField("都道府県", max_length=200)
    done = models.CharField("ジャンル", max_length=200)
    person = models.CharField("人数", max_length=200)
    day = models.CharField("旅行日数", max_length=200)
    plan_name = models.CharField("プラン名", max_length=200)
    plan_detail = models.TextField("プラン詳細")
    typeno = models.IntegerField

    class Meta:
        db_table = 'plan'
        verbose_name = 'プラン'
        verbose_name_plural = 'プラン一覧'

        def __str__(self):
            return self.name

torapuraapp/forms.py
from django import forms
from .models import Plan

class PlanSearchForm(forms.Form):
    place = forms.ChoiceField(
        choices=[('', '都道府県を選択してください')] + [
        ('北海道', '北海道'),
        ('青森県', '青森県'),
        ('岩手県', '岩手県'),
        ('秋田県', '秋田県'),
        ('宮城県', '宮城県'),
        ('山形県', '山形県'),
        ('栃木県', '栃木県'),
        ('和歌山県', '和歌山県'),
        ('島根県', '島根県'),
        ('高知県', '高知県'),
        ('愛媛県', '愛媛県'),
        ('長崎県', '長崎県'),
        ('大分県', '大分県'),
        ('熊本県', '熊本県'),
        ('鹿児島県', '鹿児島県'),
    ],
    initial='')

    done = forms.ChoiceField(
        choices=[('', 'ジャンルを選択してください')] + [
        ('activity', 'スポーツ'),
        ('sightseeing', '観光'),
    ],
    initial='')

    person = forms.ChoiceField(
        choices=[('', '旅行人数を選択してください')] + [
        ('1～2人', '1～2人'),
        ('3人以上', '3人以上'),
    ],
    initial='')

    day = forms.ChoiceField(
        choices=[('', '旅行日数を選択してください')] + [
        ('日帰り', '日帰り'),
        ('1泊2日', '1泊2日'),
        ('2泊3日', '2泊3日'),
        ('3泊4日', '3泊4日'),
    ],
    initial='')

    keyword = forms.CharField(
        required=False,
        label='キーワード',
        widget=forms.TextInput(attrs={'placeholder': 'キーワードを入力'}))

torapuraapp/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .models import Plan
from .forms import PlanSearchForm
import random
from .models import Post
from django.views.generic import ListView

class IndexView(TemplateView):
    # index.htmlをレンダリングする
    template_name = "index.html"


class GalleryView(TemplateView):
    template_name = "gallery.html"


class ContactView(TemplateView):
    template_name = "contact.html"


class ContactUserView(TemplateView):
    template_name = "contact_user.html"


class ContactCompanyView(TemplateView):
    template_name = "contact_company.html"

class Post_List_View(ListView):
    template_name = "gallery.html"
    model = Post
    context_object_name = "posts"

class PlanView(TemplateView):
    template_name = "plan.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = PlanSearchForm(self.request.GET or None)
        context['form'] = form
        return context

class PlanResultView(TemplateView):
    template_name = "plan_result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = PlanSearchForm(self.request.GET or None)
        if form.is_valid():
            place = form.cleaned_data['place']
            done = form.cleaned_data['done']
            person = form.cleaned_data['person']
            day = form.cleaned_data['day']
            keyword = form.cleaned_data['keyword']
            plans = Plan.objects.filter(place=place, done=done, person=person, day=day)
            if keyword:
                plans = plans.filter(plan_detail__icontains=keyword)
            plans = list(plans)
            if plans:
                context['plan'] = random.choice(plans)
            else:
                context['plan'] = None
            # 選んだ条件をコンテキストに追加
            # doneの値を置き換え
            if done == 'activity':
                done_display = 'スポーツ'
            else:
                done_display = '観光'
            context['selected_conditions'] = {
                'place': place,
                'done': done_display,
                'person': person,
                'day': day,
                'keyword': keyword,
            }
        else:
            context['plan'] = None
            context['selected_conditions'] = {}
        return context

torapuraapp/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>お問い合わせ</title>
    <link rel="stylesheet" href={% static 'css/style.css' %} />

</head>
<body> 
 
 
   <!--<h1><img src="images/torapura.png" alt="とらぷら" width="300px"></h1>-->
   <div class="header">
    <nav class="navbar">
      <h2 class="logo">TravelPlanner</h2>
      <ul class="menu">
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

        <li class="menu-item">
          <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
          <ul class="drop-menu-list">
             <li class="drop-menu-item">
                <li class="cuurent"><a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
             </li>
             <li class="drop-menu-item">
                <a href="{% url 'torapuraapp:contact_user' %}">利用者向け</a>
             </li>
          </ul>
        </li>
      </ul>
    </nav>
   </div>

  <nav>
    <ol class="breadcrumb">
      <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
      <li>お問い合わせ</li>
    </ol>
  </nav>

  <main>
    <li><a href="{% url 'torapuraapp:contact_company' %}">お問い合わせ（企業向け）</a>
    <li><a href="{% url 'torapuraapp:contact_user' %}">お問い合わせ（利用者向け）</a>
  </main>

  <!--フッター-->
  <footer>
    <div id="footer_nav">
    <ul>
      <li><a href="{% url 'torapuraapp:index' %}">HOME</a></li>
      <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
      <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
      <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
        
    </ul>
    </div>
    <small>&copy;  2024 とらぷら.</small>
  </footer>
 <!--/フッター-->

</body>
</html>

torapuraapp/templates/contact_company.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>お問い合わせ（企業向け）</title>
    <link rel="stylesheet" href={% static 'css/style.css' %} />

</head>
<body> 
 
 
   <!--<h1><img src="images/torapura.png" alt="とらぷら" width="300px"></h1>-->
   <div class="header">
    <nav class="navbar">
      <h2 class="logo">TravelPlanner</h2>
      <ul class="menu">
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

        <li class="menu-item">
          <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
          <ul class="drop-menu-list">
             <li class="drop-menu-item">
                <li class="cuurent"><a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
             </li>
             <li class="drop-menu-item">
                <a href="{% url 'torapuraapp:contact_user' %}">利用者向け</a>
             </li>
          </ul>
        </li>
       
      </ul>
    </nav>
   </div>

  <nav>
    <ol class="breadcrumb">
      <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
      <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
      <li>企業向け</li>
    </ol>
  </nav>

<main>
  <h2>お問い合わせフォーム(企業向け)</h2>

  <form action="">
    <input type="email" placeholder="メールアドレス" name="company_email" required>
    <input type="text" placeholder="企業名" name="company_name" required>
    <input type="text" placeholder="件名" name="title" required>
    <textarea placeholder="本文" name="message" required></textarea>
    <input type="file" placeholder="写真を選択"  name="image" required>
    <input type="submit" value="送信">
</main>
    


  <!--フッター-->
  <footer>
    <div id="footer_nav">
    <ul>
      <li><a href="{% url 'torapuraapp:index' %}">HOME</a></li>
      <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
      <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
      <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
        
    </ul>
    </div>
    <small>&copy;  2024 とらぷら.</small>
  </footer>
 <!--/フッター-->

</body>
</html>

torapuraapp/templates/contact_success.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>とらぷら|お問い合わせ(自治体向け)</title>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
<link rel="stylesheet" href={% static 'css/style.css' %}>


</head>
<body> 
 
 
   <!--<h1><img src="images/torapura.png" alt="とらぷら" width="300px"></h1>-->
   <div class="header">
    <nav class="navbar">
      <h2 class="logo">TravelPlanner</h2>
      <ul class="menu">
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

        <li class="menu-item">
          <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
          <ul class="drop-menu-list">
             <li class="drop-menu-item">
                <a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
             </li>
             <li class="drop-menu-item">
                <a href="{% url 'torauraapp:contact_user' %}">利用者向け</a>
             </li>
          </ul>
        </li>
       
      </ul>
    </nav>
   </div>

  <nav>
    <ol class="breadcrumb">
      <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
      <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
      <li>企業向け</li>
    </ol>
  </nav>

  <main>
    <h2>
      お問い合わせの送信が完了しました。
    </h2>
  </main>

  <input type="button" onclick="location.href={% url 'toraouraapp:index' %}" value="ホームに戻る">

  

  <!--フッター-->
  <footer>
    <div id="footer_nav">
    <ul>
      <li><a href="{% url 'torapuraapp:index' %}">HOME</a></li>
      <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
      <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
      <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
        
    </ul>
    </div>
    <small>&copy;  2024 とらぷら.</small>
  </footer>
 <!--/フッター-->

</body>
</html>

torapuraapp/templates/gallery.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>ギャラリー</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
  <link rel="stylesheet" href="{% static 'style.css' %}">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>


</head>

<body>
  <div class="header">
    <nav class="navbar">
      <h2 class="logo">TravelPlanner</h2>
      <ul class="menu">
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li class="current"><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
        <li class="menu-item">
          <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
          <ul class="drop-menu-list">
            <li class="drop-menu-item">
              <a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
            </li>
            <li class="drop-menu-item">
              <a href="{% url 'torapuraapp:contact_user' %}">利用者向け</a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>

  <nav>
    <ol class="breadcrumb">
      <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
      <li>ギャラリー</li>
    </ol>
  </nav>


  <main>
    <h1>ブログ投稿一覧</h1>
    <div class="layout modal">
      <div class="modal__cards">
        {% for post in posts %}
        <!-- モーダルウィンドウを開くカード -->
        <div class="modal__card card">
          <div class="card__picture">
            {% if post.image %}
              <img src="{{ post.image.url }}" alt="{{ post.title }}">
            {% endif %}
          </div>
          <div class="card__main">
            <h2 class="card__title"><a>{{ post.title }}</a></h2>
            <p class="card__text">{{ post.content }}</p>
            <p class="card__date">{{ post.date }}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  
    <!-- モーダルウィンドウが開いた時の背景 -->
    <div id="modal-visible" class="modal__background">
      <div id="create-card" class="card js-card-close">
        <div id="modal-picture" class="card__picture">
          <img src="#" alt="">
        </div>
        <div class="card__main">
          <h2 id="modal-title" class="card__title"></h2>
          <p id="modal-text" class="card__text"></p>
          <p id="modal-date" class="card__date"></p>
        </div>
        <!-- モーダルウィンドウを閉じるボタン -->
        <div id="modal-close" class="modal__close">
          <div class="modal__icon"></div>
        </div>
      </div>
    </div>

    <script>
      $(function(){
  
        var card = $('.card'),
        modal_visible = $('#modal-visible'),
        close = $('#modal-close');
  
        card.on('click', function() {
          // クリックされたカードが js-card-close クラスを持っているかを確認
          // 既に js-card-close クラスがある場合、モーダルを表示しない
          if ($(this).hasClass('js-card-close')) {
            return;
          }
  
          // クリックしたカードの情報を取得
          var imgSrc = $(this).find('.card__picture img').attr('src');
          var imgAlt = $(this).find('.card__picture img').attr('alt');
          var title = $(this).find('.card__title').text();
          var text = $(this).find('.card__text').text();
          var date = $(this).find('.card__date').text();
  
          // モーダルで表示したカードに情報を反映
          $('#modal-picture img').attr('src', imgSrc).attr('alt', imgAlt);
          $('#modal-title').text(title);
          $('#modal-text').text(text);
          $('#modal-date').text(date);
  
          modal_visible.addClass('visible');
        });
  
        // ×アイコンをクリックしたらモーダルを閉じる
        close.on('click', function(){
          modal_visible.removeClass('visible');
        });
  
        // モーダルの外側をクリックしたらモーダルを閉じる
        modal_visible.on('click', function(event) {
          // クリックした要素がカードの部分であれば処理を中止する
          if ($(event.target).closest(card).length === 0) {
            modal_visible.removeClass('visible');
          }
        });
      });
    </script>
  </main>

  <!--フッター-->
  <footer>
    <div id="footer_nav">
      <ul>
        <li><a href="{% url 'torapuraapp:index' %}">HOME</a></li>
        <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
        <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

      </ul>
    </div>
    <small>&copy; 2024 とらぷら.</small>
  </footer>
  <!--/フッター-->

</body>

</html>

torapuraapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ホーム</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" href="{% static 'css/swiperstyle.css' %}">

</head>

<body>
  <div class="header">
    <nav class="navbar">
      <h2 class="logo">TravelPlanner</h2>
      <ul class="menu">
        <li class="current"><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>

        <li class="menu-item">
          <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
          <ul class="drop-menu-list">
            <li class="drop-menu-item">
              <a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
            </li>
            <li class="drop-menu-item">
              <a href="{% url 'torapuraapp:contact_user' %}">利用者向け</a>
            </li>
          </ul>
        </li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

      </ul>
    </nav>
  </div>

  <nav>
    <ol class="breadcrumb">
      <li>ホーム</li>
    </ol>
  </nav>


  <div id="wrapper">
    <!--メイン-->
    <div id="main">
      <section id="point">
        <h2>おすすめプラン</h2>
        <iframe src="{% static 'swiper/swiper.html' %}" width="400" height="400"></iframe>

    </div>
  </div>

  <footer>
    <div id="footer_nav">
      <ul>
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
        <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
      </ul>
    </div>
    <small>&copy; 2024とらぷら.</small>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
</body>

</html>

torapuraapp/templates/plan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>プラン作成</title>
    <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %} />
    

  </head>

  
  <body>
    <div class="header">
      <nav class="navbar">
        <h2 class="logo">TravelPlanner</h2>
        <ul class="menu">
          <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
          <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
          <li class="current"><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

          <li class="menu-item">
            <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
            <ul class="drop-menu-list">
               <li class="drop-menu-item">
                  <a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
               </li>
               <li class="drop-menu-item">
                  <a href="{% url 'torapuraapp:contact_user'}">利用者向け</a>
               </li>
            </ul>
          </li>
         
        </ul>
      </nav>
    </div>
  
    <nav>
      <ol class="breadcrumb">
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li>プラン作成</li>
      </ol>
    </nav>
    
    
    <form method="get" action="{% url 'torapuraapp:plan_result' %}">
      <h1>プラン作成</h1>
      <h2>条件やキーワードを入力してプラン作成</h2>
      <div class="form-container">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group">
                {{ form.place }}
            </div>
            <div class="form-group">
                {{ form.done }}
            </div>
            <div class="form-group">
                {{ form.person }}
            </div>
            <div class="form-group">
                {{ form.day }}
            </div>
        </div>
        {{ form.keyword }}
      <input type="submit" value="プラン作成">
      </div>
    </form>

    <script>
      const menu = document.querySelector(".menu");
      const navbar = document.querySelector(".navbar");
      window.addEventListener("scroll", () => {
        if (window.pageYOffset >= menu.offsetTop) {
          navbar.classList.add("sticky");
        } else {
          navbar.classList.remove("sticky");
        }
      });
    </script>





    <footer>
      <div id="footer_nav">
         <ul>
          <li><a href="{% url 'torapuraapp:index' %}">HOME</a></li>
          <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
          <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
          <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
         </ul>
      </div>
      <small>&copy; 2024とらぷら.</small>
    </footer>

   <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  </body>
</html>

torapuraapp/templates/plan_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>プラン作成</title>
    <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %} />
    

  </head>

  
  <body>
    <div class="header">
      <nav class="navbar">
        <h2 class="logo">TravelPlanner</h2>
        <ul class="menu">
          <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
          <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
          <li class="current"><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>

          <li class="menu-item">
            <a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a>
            <ul class="drop-menu-list">
               <li class="drop-menu-item">
                  <a href="{% url 'torapuraapp:contact_company' %}">企業向け</a>
               </li>
               <li class="drop-menu-item">
                  <a href="{% url 'torapuraapp:contact_user'}">利用者向け</a>
               </li>
            </ul>
          </li>
         
        </ul>
      </nav>
    </div>
  
    <nav>
      <ol class="breadcrumb">
        <li><a href="{% url 'torapuraapp:index' %}">ホーム</a></li>
        <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
        <li>プラン作成結果</li>
      </ol>
    </nav>
    <div class="plan-result">
        <h1>プラン作成結果</h1>
        {% if selected_conditions.keyword  %}
            <h2>選んだ条件：{{ selected_conditions.place }}、{{ selected_conditions.done }}、{{ selected_conditions.person }}、{{ selected_conditions.day }}、{{ selected_conditions.keyword }}</h2>
        {% else %}
            <h2>選んだ条件：{{ selected_conditions.place }}、{{ selected_conditions.done }}、{{ selected_conditions.person }}、{{ selected_conditions.day }}</h2>
        {% endif %}
    </div>
    <div class="plan-detail">
        {% if plan %}
            <h2>{{ plan.plan_name }}</h2>
            <p>{{ plan.plan_detail|linebreaksbr }}</p>
        {% else %}
            <h2>条件に合ったプランが見つかりませんでした。</h2>
        {% endif %}
    </div>
    <script>
      const menu = document.querySelector(".menu");
      const navbar = document.querySelector(".navbar");
      window.addEventListener("scroll", () => {
        if (window.pageYOffset >= menu.offsetTop) {
          navbar.classList.add("sticky");
        } else {
          navbar.classList.remove("sticky");
        }
      });
    </script>





    <footer>
      <div id="footer_nav">
         <ul>
          <li><a href="{% url 'torapuraapp:index' %}">HOME</a></li>
          <li><a href="{% url 'torapuraapp:gallery' %}">ギャラリー</a></li>
          <li><a href="{% url 'torapuraapp:contact' %}">お問い合わせ</a></li>
          <li><a href="{% url 'torapuraapp:plan' %}">プラン作成</a></li>
         </ul>
      </div>
      <small>&copy; 2024とらぷら.</small>
    </footer>

   <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  </body>
</html>